# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
name: java-build

on:
  push:
    paths:
      - 'java/**'
      - '.github/workflows/maven.yml'
    branches:
      - master
      - release-*
  
  # Enable manually triggering
  workflow_dispatch:

  # Run build for any PR
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/maven.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8' ]

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: build with Maven
      working-directory: java
      run: mvn verify javadoc:jar source:jar --batch-mode --errors --quiet -DcreateJavadoc=true --file pom.xml --settings .maven.settings.xml
