# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
name: javascript-build

on:
  push:
    paths:
      - 'javascript/**'
      - '.github/workflows/nodejs.yml'
    branches:
      - master

  # Run build for any PR
  pull_request:
    paths:
      - 'javascript/**'
      - '.github/workflows/nodejs.yml'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16', '18']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: javascript
      run: |
        npm ci
        npm run lint
        npm run build
        npm test
      env:
        CI: true
